# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build-landing-page:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "landing-page/package-lock.json" }}
      - run: cd landing-page && npm install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "landing-page/package-lock.json" }}
          paths:
            - "landing-page/node_modules"
      #- run: cd landing-page && npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      #- run: cd landing-page && npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
      - run: cd landing-page && npm run build-prod

  build-chrome:
    docker:
      - image: circleci/openjdk:8-jdk-node

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - chrome-cache-v1-{{ checksum "chrome/build.sbt" }}-{{ checksum "chrome/project/plugins.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - chrome-cache-v1-

      # sometimes this fails due to memory issues while retrying succeeds, also, compiling the lib modules independetly should help
      - run: cd lib && sbt commonJVM/compile && sbt apiJVM/compile && sbt commonJS/compile && sbt apiJS/compile && (sbt ui/compile || sbt ui/compile)
      - run: cd chrome && (sbt compile || sbt compile || sbt compile)

      - save_cache:
          paths:
            - ~/.cache/coursier
            - ~/.ivy2
            - ~/.m2
          key: chrome-cache-v1-{{ checksum "chrome/build.sbt" }}-{{ checksum "chrome/project/plugins.sbt" }}

      # run tests!
      # - run: cd chrome && sbt test

      # package
      - run: cd chrome && sbt chromePackage

  build-pwa:
    docker:
      - image: circleci/openjdk:8-jdk-node

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - pwa-cache-v1-{{ checksum "pwa/build.sbt" }}-{{ checksum "pwa/project/plugins.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - pwa-cache-v1-

      - run: cd pwa && sbt test:compile

      - save_cache:
          paths:
            - ~/.cache/coursier
            - ~/.ivy2
            - ~/.m2
          key: pwa-cache-v1-{{ checksum "pwa/build.sbt" }}-{{ checksum "pwa/project/plugins.sbt" }}

      # run tests!
      # - run: cd pwa && sbt test

      # package
      - run: cd pwa && sbt build

workflows:
  version: 2
  build:
    jobs:
      - build-landing-page
      # disabled because circleci runs out of memory
      # - build-chrome
      - build-pwa
